% DEMO_SENSOR_CONFIG Ejemplo de definición sensor por sensor.

sensors(1) = struct( ...
    'SamplingHz', 250, ...
    'SensorID', 'A1', ...
    'Format', 'miniseed', ...
    'Channels', 3, ...
    'Factor', 3.815, ...
    'Range', '+/-2g', ...
    'Orientation', {'-Y','-X','+Z'}, ...
    'UTCStart', datetime('now', 'TimeZone', 'UTC'), ...
    'SerialNumber', 'W25641');

sensors(2) = struct( ...
    'SamplingHz', 100, ...
    'SensorID', 'B2', ...
    'Format', 'txt', ...
    'Channels', 1, ...
    'Factor', 1.2, ...
    'Range', '+/-4g', ...
    'Orientation', '+X', ...
    'UTCStart', '2026-02-28T10:00:00');

sensorTable = buildSensorTable(sensors);
disp(sensorTable);
